### ISSUE TITLE
V10 compatibility

### ISSUE THREAD

**Issue by morgan613** [SDoehren/always-centred#10]
Hi! I love your module! It makes playing foundry a more intuitive and smooth experience for me and my players. I recently upgraded to V10 of foundry and was wondering if there are any plans to make this module compatible with V10? No matter what, thanks for all the great work you have done!

**Comment by SDoehren** [comment]
I will look into it.  
Basically comes down to how much of a pain it is.  
I will let you know when I have had a look.

**Comment by morgan613** [comment]
That sounds great and all one can hope for! Thank you for looking into it and developing this awesome module!

**Comment by morgan613** [comment]
Hi! I was wondering what the result of the investigation was. Either way is fine but I'm curious if you think you will update the module for Foundry v10 or not. Regardless, thanks for all you've done!

**Comment by SDoehren** [comment]
Based on the upgrade for another one of my other modules there will be a fundamental change in part of the module (the scene controls on the left will be replaced with macros), but other than that I should be able to upgrade when I get a moment to give it a deep dive.

**Comment by morgan613** [comment]
Oh wonderful! Thank you very much!!

**Comment by Mellowub** [comment]
> Based on the upgrade for another one of my other modules there will be a fundamental change in part of the module (the scene controls on the left will be replaced with macros), but other than that I should be able to upgrade when I get a moment to give it a deep dive.

Hiya @SDoehren , really love this module, has always been a keeper for all the campaigns I've done on foundry, wanted to let you know we appreciate the work you put in! Was gonna ask to see how's the fix been goin, and if it's coming up anytime soon?

**Comment by SDoehren** [comment]
I have just had a campaign end so have fully moved to V10 myself.  My target is to have this switched over this year.

**Comment by Mellowub** [comment]
> 

good news ! hopefully it'll be easy to get it through ! the module is amazing, my mates can't live without it LOL

**Comment by SDoehren** [comment]
V10 version released
