### ISSUE TITLE
[BUG] module seems not to work with "selected token option"

### ISSUE THREAD

**Issue by Moze75** [SDoehren/always-centred#11]
**Describe the bug**
The module seems not to work with the "selected token" option. Nothing happen for the GM or the players.
It works with "Party view" option

**Foundry **
 - Foundry Version 10
 - System [DnD5e]
 - Module Version 007 [LATEST]

**Desktop **
 - OS: [windows 10]
 - Browser [Mozilla]
 - Version 107.01

Thanks for your answer

**Comment by SDoehren** [comment]
New version released, should resolve this.

**Comment by Moze75** [comment]
Perfect, works like a charm !
