### ISSUE TITLE
Seems to be v11 compatible :) - but versioning is a bit confusing

### ISSUE THREAD

**Issue by coffiarts** [SDoehren/always-centred#12]
This may not be a "hard" bug report, but I can't find a better place for my question. I apologize in advance if this should be the wrong "channel".

First of all, the good part: It seems to me that this mod (which I really love!) runs fine in Foundry v11.
Might be good to know for others and the author.

My question is: Why do the versions given in the release (V0008) and the module.json (0087) differ?

Probably isn't a big issue. It's only that I plan to add always-centred as "recommended" dependency to one of my own mods(as this is something the new Foundry version 11 supports): https://github.com/coffiarts/FoundryVTT-hot-pan
So I am uncertain what version to put there as "verified version".

![image](https://github.com/SDoehren/always-centred/assets/39616483/90449064-cf0c-44d3-b723-6a469c034c16)

Any clarification on that would help.

**Comment by SDoehren** [comment]
The V11 compatibility is great to know, thanks.

The Version issue is a typo somewhere along the line.

I actually recommend using Monk's Common Display for what Always Centred is
designed for.
Always Centred will be updated rarely going forwards.
I'm happy to help you implement the relevant bits into your code.  It is a
fairly simple module if you ignore the collisions it has with some bigger
modules.

**Comment by coffiarts** [comment]
Thanks for replying so rapidly!
Of course I can understand if you have chosen not to maintain this mod to a full extend and want to focus more on development for private use.
It's also very respectable that - instead of simply letting it "dry out" - you're pointing people to another mod that will carry on your idea!
But I'd still like to mention that I specifically like your mod, because it does a very nice and specific thing quite reliably, and in an easy-to-understand way. Whereas Monk's Common Display - as sophisticated it may be - does a whole lot more stuff, which I probably won't need.
Even more, practically speaking, Always Centred _does_ already work with v11, whereas Common Display apparently does not (just ran an unsuccessful test), and there's litte hint on wheter or when it will be migrated.
That's why I really hope that this nice little mod here won't get comletely abandoned. :)

**Comment by phenomen** [comment]
"Hot Pan & Zoom" has this module as a dependency and it would be nice to bump max Foundry version here

**Comment by coffiarts** [comment]
> "Hot Pan & Zoom" has this module as a dependency and it would be nice to bump max Foundry version here

I (as the creator of Hot Pan & Zoom) feel a bit guilty here for having added always-centred as a dependency, though its author has clearly stated that it has been desupported. Therefore I should mention that it's only an _optional_ dependancy. Furthermore, it's not meant by me in _any_ way to put stress on another mod author. Even more, right now, always-centred seems to work perfectly with Foundry 11. However, if SDoehren wouldn't object, one of us could pick it up and update it by a pull request? I guess it's not a big thing, probably just some declarations in module.json.

**Comment by coffiarts** [comment]
@phenomen I suggest I'll just give it a try (and create a Pull Request within a couple of days)

**Comment by coffiarts** [comment]
@SDoehren - Here's my pull request for v11 compatibility: https://github.com/SDoehren/always-centred/pull/13
Feel free to merge.
CC: @phenomen

**Comment by SDoehren** [comment]
Sorry everyone, dead busy.   
Merged, I will try to do a release tomorrow.

**Comment by coffiarts** [comment]
@SDoehren - btw, concerning builing a release, you might want to consider automating that very easily. It requires only two small additional scripts in your github workflow directory, plus changing one repo setting. After that, releases are automatically built whenever something is commited or merged to the master branch.
It's very nicely explained here in a video: https://www.youtube.com/watch?v=raM_Z0e7ov8
As an example, this is what it looks like in my own mod: https://github.com/coffiarts/FoundryVTT-hot-pan/tree/master/.github/workflows

**Comment by SDoehren** [comment]
@coffiarts amazing.  I have implemented that now.

**Comment by coffiarts** [comment]
How wonderful - auto-update works for me now like charm:
![image](https://github.com/SDoehren/always-centred/assets/39616483/4f25e285-4745-4398-a177-ce729f9400e4)

**Comment by coffiarts** [comment]
However.... versions showing up inside FoundryVTT setup still look wrong. Could it be that the package details under https://foundryvtt.com/admin/packages/package/ are still outdated? At least that's the only thing I can imagine, as your versions in module.json look valid to me.
![image](https://github.com/SDoehren/always-centred/assets/39616483/195b7f87-ebcc-431e-b387-fb0af1c4a091)
![image](https://github.com/SDoehren/always-centred/assets/39616483/b7fb56cc-3793-48ce-9dd1-edcb20b5c85c)

**Comment by coffiarts** [comment]
Seems to be as guessed: https://foundryvtt.com/packages/always-centred (your package info in admin isn't updated yet).
![image](https://github.com/SDoehren/always-centred/assets/39616483/71806fbb-254d-45c0-8412-c5ffa89de655)

**Comment by SDoehren** [comment]
Ha ha, I always forget that system.  My modules are forever out of date in there!

Updated.

**Comment by coffiarts** [comment]
Looks nice now! Thanks alot!

**Comment by coffiarts** [comment]
Closed as completed

**Comment by SDoehren** [comment]
@coffiarts Are you on discord? If so, can you jump on my server and flick me a message https://discord.gg/QNQZwGGxuN

**Comment by coffiarts** [comment]
@SDoehren thanks for the invite. I've sent you a friendship request on discord (don't get confused by the differing nickname, see my message there in the #help channel)
