### ISSUE TITLE
Request: Always Centred on Combat Turn

### ISSUE THREAD

**Issue by Mimmitar** [SDoehren/always-centred#2]
Really enjoying this module and marking tracking our group for twitch much easier. For combat it would be awesome if it could automatically track whoever's combat turn it was as a 3rd option to party/selection.

**Comment by SDoehren** [comment]
Thank you - streaming was the original use case!

That's a great idea! 

I have added it to the "Changes under consideration" and I will 100% look into it.  
Should be relatively simple.

Closing as a suggestion and not an ongoing issue.

**Comment by SDoehren** [comment]
Also, allow me to suggest this macro for streaming, it removes all of the stuff around the screen and just shows the chat:

document.getElementById("navigation").remove();
document.getElementById("controls").remove();
document.getElementById("hotbar").remove();
document.getElementById("players").remove();
document.getElementById("chat-controls").remove();
document.getElementById("chat-form").remove();


var tabs = document.querySelectorAll("a[title='Combat Tracker'], a[title='Scenes Directory'], a[title='Actors Directory'], a[title='Items Directory'], a[title='Journal Entries'], a[title='Rollable Tables'], a[title='Audio Playlists'], a[title='Compendium Packs']");

var tabs= Array.prototype.slice.call(tabs);

tabs.forEach(function(child){
  child.parentNode.removeChild(child);
});
