### ISSUE TITLE
"GM Contol all users pan and zoom?" does not work when Token is invisible

### ISSUE THREAD

**Issue by KrapfalAT** [SDoehren/always-centred#3]
"GM Contol all users pan and zoom?" does not work when Token is set to invisible

**Comment by SDoehren** [comment]
Do you have include invisible active?

**Comment by KrapfalAT** [comment]
Yes, to be more specific pan works but zoom does not

**Comment by SDoehren** [comment]
Okays, user side, gm side or everyone problem?

**Comment by KrapfalAT** [comment]
everyone problem!

**Comment by SDoehren** [comment]
I think I have caught it.   
I will aim to get a release out over the next day or so.

**Comment by SDoehren** [comment]
New release 0.2.04 should resolve this issue.
Let me know if it does and I will reopen.

**Comment by KrapfalAT** [comment]
Its working, thanks a lot :D
