### ISSUE TITLE
"GM Control all users pan and zoom?" Setting does not safe

### ISSUE THREAD

**Issue by KrapfalAT** [SDoehren/always-centred#4]
Hi,

With the newest Version i noticed that the "GM Control all users pan and zoom?" checkbox is always unchecked when i reload my Foundry Page.
Same thing happens when i log out and log back in.
So i think the checkbox simply does not save its state when reloading the page.

**Comment by SDoehren** [comment]
I will have a look; i think i know what is causing it.
What hosting method are you using?

**Comment by KrapfalAT** [comment]
i am hosting Foundry on an Ubuntu VM on my homeserver as an NodeJS Service

**Comment by SDoehren** [comment]
New release resolves issue.  Thanks for highlighting.
