### ISSUE TITLE
Not work in sandbox system

### ISSUE THREAD

**Issue by cnutenor** [SDoehren/always-centred#5]
Can you check if its posible use in sandbox system?

**Comment by SDoehren** [comment]
Hi

I have just tested in sandbox.

Is the issue with selected token mode or party mode?

**Comment by cnutenor** [comment]
Hi i have problems in party mode.

**Comment by SDoehren** [comment]
Have you set the actors to have owners?

**Comment by SDoehren** [comment]
closed awaiting further details.
