### ISSUE TITLE
[Withdrawn] Zoom Level Additions

### ISSUE THREAD

**Issue by Shuggaloaf** [SDoehren/always-centred#6]
Hi @SDoehren, first just want to say this mod is great. Such a simple concept that has really added so much to the game. Thank you!

After using this for several months, one thing that has never worked well for me is the auto-zoom. It sets an arbitrary zoom level (.60) that is a little too zoomed out for me and the players. Because of that, I've always had to play with the auto-zoom off. 

What would be amazing is if you could add 1 or 2 of the following:
1. Allow GMs to set that default zoom percent. Custom default zoom for Global (all scenes) would work fine but Per Scene would be even better!
AND/OR
2. Allow GMs to set the Minimum Zoom level as well. This could be useful on it's own but also if #1 is too difficult to implement then this could be used for the same purpose. 

If only one option is feasible, for me #1 would be the most important. 

Thanks!

**Comment by SDoehren** [comment]
>  ​After using this for several months, one thing that has never worked well for me is the auto-zoom. It sets an arbitrary zoom level (.60) that is a little too zoomed out for me and the players. Because of that, I've always had to play with the auto-zoom off.


This sounds like a mix of the 2 Padding options, and the max zoom level.    
fiddle with the numbers.

I would suggest changing to:  
Padding squares - 6  
Padding % - 0
Max zoom - 4

then fiddle with the 2 padding options, to find your preferred settings.

> What would be amazing is if you could add 1 or 2 of the following:

To be honest, the next upgrade will be 0.8.6 compatibility.  

1 is viable and I will investigate.  
2 is a bug waiting to happen; if the minimum is set too close and it is set to party mode, it will cause a bounce effect to occur.  All the same, I will have a look into it.

**Comment by Shuggaloaf** [comment]
> fiddle with the numbers.

Ah I see. That will be great if that's all it is. Will give it a go shortly and report back.

>2 is a bug waiting to happen

I see your point. Honestly 2 was more of an alternative to 1 anyway, but that I thought could be useful. However I can understand the issue you mentioned so I have no problem withdrawing that as a suggestion.

**Comment by Shuggaloaf** [comment]
That was it my friend! Thank you for the quick response on this one. 
Personally, I would just withdrawal both of these now that I understand how padding affects the zoom. I know you said you may investigate 1 but I'm of the "if it ain't broke don't fix it" philosophy. Works well as is. 

Now that I look at your read me, the padding description makes sense. Guess I just never played with it and wasn't thinking about it in terms of how it affects zoom. 

My vote here would be forget any suggested mod changes I made and - for dummies like me that need a brick to the face - revise padding description to something like this: 
>Padding (squares): (default:12)
> The number squares added to the box around the targets. Affects the minimum zoom level. Lower number = more zoomed in, higher number = more zoomed out.

Thank you again for your responsiveness and your work on this great mod!

**Comment by SDoehren** [comment]
Great, thanks for the notes.

I will probably still explore number 1 as bounding both ends is likely a good idea.

I have added a note to Max zoom level "0.1 is far away, 3 is very close"; I will add notes to the others.
